version: '3.8'

services:
  deepface-img2img:
    build:
      context: .
      dockerfile: dockerfile
    image: deepface-img2img
    container_name: deepface-img2img
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./model:/app/model
      - ./utils:/app/utils
      - ./assets:/app/assets
    environment:
      - MODEL=/app/model/model_swap_face.onnx
      - MODEL_CODEFORMER=/app/src/CodeFormer/CodeFormer/weights/CodeFormer/codeformer.pth
      - FULL_GENERATE=True
      - DIM_EMBD=512
      - CODEBOOK_SIZE=1024
      - N_HEAD=8
      - N_LAYERS=9
      - CONNECT_LIST=["32", "64", "128", "256"]
      - SOURCE_INDEXES="-1"
      - TARGET_INDEXES="-1"
      - FACE_RESTORE=store_true
      - BACKGROUND_ENHANCE=store_true
      - FACE_UPSAMPLE=store_true
      - UPSCALE=1
      - CODEFORMER=0.5
      - SOURCE_PATH=temp_source.jpg
      - TARGET_PATH=temp_target.jpg
      - HOST=0.0.0.0
      - PORT=3000
    command: python app.py

volumes:
  model_data:
  src_data:
  utils_data:
  assets_data:

# docker-compose up --build
# docker-compose up --build -d # (ทำงานเบื้องหลัง)
# docker-compose down